services:
  postgres:
    image: postgres:16
    container_name: core-server-db
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_pass
      POSTGRES_DB: core_server
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U core_user -d core_server"]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_storage:/qdrant/storage

    restart: unless-stopped



volumes:
  pgdata:
  qdrant_storage:
